### PR TITLE
Fix destructured prop types

### LINKED ISSUE #24: Proptypes plugin fails when proptypes are destructured
The prop types plugin fails to properly convert proptypes to TS types when the proptypes import is destructured. See the below example:

```
import React from "react";
import { node, string } from "prop-types";

const Foo = ({ children, className }) => {
  return <div className={className}>children</div>;
};

Foo.propTypes = {
  children: node,
  className: string,
};

export default Foo;
```

Relevant code:
https://github.com/airbnb/ts-migrate/blob/master/packages/ts-migrate-plugins/src/plugins/utils/react-props.ts#L115

The check on this line fails and a type reference node is created instead. Not sure what the best solution would be but it would probably involve keeping track of the identifiers from the import of `prop-types`. Happy to hear any pointers and I could take a stab at writing a PR for it.

### PR DESCRIPTION
**Pull request by arthuralee**
Fixes the case where we use `import { string } from "prop-types"` instead of `import PropTypes from "prop-types"`

Fixes #24

### CODE REVIEW

**Comment by Rudeg** [comment]
hi @arthuralee, thanks for the contribution! is it ready for review?

File: packages/ts-migrate-plugins/src/plugins/react-props.ts [hunk 1]
```diff
@@ -28,11 +30,30 @@ const reactPropsPlugin: Plugin<Options> = {
     const updates: SourceTextUpdate[] = [];
     const getPropsTypeName = createPropsTypeNameGetter(sourceFile);
 
+    // Scan for prop type imports
+    const propTypeIdentifiers: PropTypesIdentifierMap = {};
+    for (const node of sourceFile.statements) {
```
Comment (Rudeg) [inline packages/ts-migrate-plugins/src/plugins/react-props.ts:35]: instead of iterating 2 times thought the `sourceFile.statements`, could we move this to the loop below?

File: packages/ts-migrate-plugins/src/plugins/react-props.ts [hunk 2]
```diff
@@ -28,11 +30,30 @@ const reactPropsPlugin: Plugin<Options> = {
...
+      if (ts.isImportDeclaration(node) && node.moduleSpecifier.getText() === '"prop-types"') {
```
Comment (Rudeg) [inline packages/ts-migrate-plugins/src/plugins/react-props.ts:36]: @arthuralee Imports are usually is the first statements of the file, maybe we can combine 2 loops into the one with a comment? 
This seems a little bit hacky, but it might prevent from doing 2nd iteration.

File: packages/ts-migrate-plugins/tests/src/react-props.test.ts [hunk 3]
```diff
@@ -1114,4 +1114,39 @@ class Foo extends React.Component<Props> {
 export default Foo;
 `);
   });
+
+  it('Handles destructuring of prop-types', async () => {
```
Comment (Rudeg) [inline packages/ts-migrate-plugins/tests/src/react-props.test.ts:1118]: thanks for adding the test!

**Comment by Rudeg** [comment]
lgtm overall, left one minor comment
thanks for the contribution, @arthuralee!

File: packages/ts-migrate-plugins/src/plugins/react-props.ts (hunk 2 above)
Comment (arthuralee) [reply packages/ts-migrate-plugins/src/plugins/react-props.ts:36]: Yeah, i used 2 loops to be 100% correct but you're probably right. will update

**Review by Rudeg — APPROVED** [review]
